version: "2.1"
services:
  registry:
    image: "registry:2"
    container_name: "private-registry"
    restart: always
    ports: 
      - "5000:5000"
    volumes:
      - /Volumes/Macintosh HD/Extends/data/docker_registry/data:/var/lib/registry
      - /Volumes/Macintosh HD/Extends/data/docker_registry/certs/auth.crt:/certs/auth.crt
    environment:
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://172.28.210.141:8000/authorize #point to registry-auth-server domain, see example nginx.conf
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
      - REGISTRY_HTTP_SECRET=""
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/auth.crt
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
    depends_on:
      - registry-log
      - registry-auth-server
      - registry-ui
    networks: 
      fluentd:
  registry-auth-server:
    image: "huyinghuan/docker-registry-auth:latest"
    container_name: "registry-auth-server"
    restart: always
    ports: 
      - "8000:8000"
    volumes:
      - /Volumes/Macintosh HD/Extends/data/docker_registry/certs/auth.crt:/go/src/docker_auth/certs/auth.crt
      - /Volumes/Macintosh HD/Extends/data/docker_registry/certs/auth.key:/go/src/docker_auth/certs/auth.key
    environment:
      - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service" #the same with registry.environment.REGISTRY_AUTH_TOKEN_SERVICE
      - REGISTRY_AUTH_TOKEN_EXPIRATION=900
      - REGISTRY_AUTH_TOKEN_DEBUG=false
      - REGISTRY_AUTH_TOKEN_ACCOUNT_USER=admin
      - REGISTRY_AUTH_TOKEN_ACCOUNT_PASS=12345678
      - REGISTRY_AUTH_TOKEN_ACCOUNT_API=__registry
      - REGISTRY_AUTH_TOKEN_ACCOUNT_DATABASE="root:12345678@tcp(db:3300)/docker_auth"
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: "docker.{{.Name}}"
    depends_on:
      db:
        condition: service_healthy
    networks: 
      fluentd:
  registry-ui:
    image: "huyinghuan/docker-registry-frontend:latest"
    container_name: "registry-ui"
    environment:
      - ENV_DOCKER_REGISTRY_SERVER=http://registry:5000
      - ENV_DOCKER_REGISTRY_UI_PORT=5001
      - ENV_DOCKER_REGISTRY_UI_AUTH=true
      - ENV_DOCKER_REGISTRY_AUTH_SERVER=http://registry-auth-serve:8000/authorize
    ports:
      - "5001:5001"
    networks: 
      fluentd:
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"
  registry-log:
    image: "fluent/fluentd:latest"
    container_name: "registry-log"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - /Volumes/Macintosh HD/Extends/data/log:/fluentd/log
    networks: 
      fluentd:
  db:
    image: mysql:latest
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: docker_auth
    ports:
      - "3300:3306"
    volumes:
      - /Volumes/Macintosh HD/Extends/data/mysqldata:/var/lib/mysql
    healthcheck: 
      test: "/usr/bin/mysql --user=root --password=12345678 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      fluentd:
networks:
  fluentd:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1