version: "2.1"
services:
  register:
    image: "registry:2"
    container_name: "private-registry"
    restart: always
    ports: 
      - "5000:5000"
    volumes:
      - /Volumes/Macintosh HD/Extends/data/docker_registry/data:/var/lib/registry
      - /Volumes/Macintosh HD/Extends/data/docker_registry/certs/auth.crt:/certs/auth.crt
    environment:
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://172.28.210.141:8000/authorize
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
      - REGISTRY_HTTP_SECRET=""
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/auth.crt
  register-auth-server:
      image: "huyinghuan/docker-registry-auth:1.0"
      container_name: "private-registry-auth-server"
      restart: always
      ports: 
        - "8000:8000"
      volumes:
        - /Volumes/Macintosh HD/Extends/data/docker_registry/certs/auth.crt:/go/src/docker_auth/certs/auth.crt
        - /Volumes/Macintosh HD/Extends/data/docker_registry/certs/auth.key:/go/src/docker_auth/certs/auth.key
      environment:
        - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
        - REGISTRY_AUTH_TOKEN_EXPIRATION=900
        - REGISTRY_AUTH_TOKEN_DEBUG=false
  register-ui:
    image: "huyinghuan/docker-registry-frontend:v2"
    container_name: "private-registry-ui"
    environment:
      - ENV_DOCKER_REGISTRY_SERVER=http://172.28.210.141:5000
      - ENV_DOCKER_REGISTRY_UI_PORT=5001
      - ENV_DOCKER_REGISTRY_UI_AUTH=true
    ports:
      - "5001:5001"
      